### PR TITLE
Add GLib.List for children

### PR DESCRIPTION
**Pull request by ItsJamie9494**

### CODE REVIEW

**Comment by lainsce** [comment]
Not sure what children is going to be used for, and why isn't list using it?

**Comment by ItsJamie9494** [comment]
Its used so that if I want to go through and clear a list, I can do a for loop on children, and delete the returned widget

**Comment by lainsce** [comment]
Right, but on add_children, add and remove, these children are being both on the new list, and on the widget list. If this is going to be used, it's better that it's only added to children, and anything added to children is added to list separately.

**Comment by ItsJamie9494** [comment]
I don't see a widget list anywhere that's accessible to an external dev

**Comment by lainsce** [comment]
I meant internally, let the external dev only handle childs via the list `children`, but not the listbox directly. The listbox should get and add/remove what children contains in a separate method.

**Comment by lainsce** [comment]
Basically, L34 should be privated, and the children list should be used to add/remove stuff to the widget.

**Comment by ItsJamie9494** [comment]
I don't care, I just need a way to access the children

**Comment by lainsce** [comment]
Yes, but to add a list that's not connected to the listbox widget will not ensure that what you get from there actually exists in the widget.

**Comment by ItsJamie9494** [comment]
I wrote that code in 2 minutes to fix a problem, if you have a better way, please imeplement it

**Comment by lainsce** [comment]
I'm sorry, but you're the contributor here bringing a PR, not me. Ensure that what you added actually does what it says. :(

**Comment by lainsce** [comment]
Y'know what, I'll merge and fix this myself...

**Pull request merged**
